### ISSUE TITLE
Suggestion - mirror an external defined member

### ISSUE THREAD

**Issue by berdal84** [Grouflon/mirror#2]
It would be great to add a mechanism to serialize members when you can't modify it's class (external library for example).

Here a small example:

```
struct A {
   ExternalClass m_member; // ExternalClass is included in a lib or from external files that you don't want to modify
   MIRROR_CLASS(A)
   (
      MIRROR_MEMBER(m_member); // will not work
   );
}
```

I propose for example:

```
struct A {
   ExternalClass m_member; // ExternalClass is included in a lib or from external files that you don't want to modify

   MIRROR_CLASS(A)
   (
      MIRROR_MEMBER(m_member, &methodToSerialize, &methodToDeserialize);
   );
}
```

These two methods should be defined by the user.

We can also imagine an other solution by defining MIRROR_CLASS and _MEMBER outside the class/struct. With internal classes, it only requires to add `friend` keyword, for external we have to use getter/setters if they exist of course...

What do you think of that ?

**Comment by Grouflon** [comment]
Indeed, I don't even think that would be great, I think that is necessary for the library to be actually usable :)
So two things, first is that I think we are not very far from it, since I already wrote internally to the lib some reflection over standard library classes. Maybe it only needs a little more rationaliziation to make it something doable from the outside.
Second, I don't think your solution is adequate, because serialization is just a use case of reflection. I don't want the serialization to be explicitely defined in the reflection code. Reflection should just be about exposing a description of what a type is, and serialization should be higher level code, written according to that description.

**Comment by berdal84** [comment]
I think I was wrong by choosing serialize/deserialize as names. Just imagine something that ony refers to reflection such as &getValue and &setValue
Then mirror should just check if the parameter of setValue function is the same type as the getValue return type. These could be lambda functions for example (again, outside the class).
Like that instead of set/get a member by reading/writing data directly to the right adress, you just call a getter/setter.
Furthermore, it is often needed to trigger something in the program when a member is modified. Mirror will be able to modify values bypassing setters, I don't know if it is a good thing.
